### ISSUE TITLE
Final music extractor tasks

### ISSUE THREAD

**Issue by alastair** [MTG/essentia#180]
- [x] Windows filenames (#177) - @alastair
- [x] High-level - @dbogdanov 
- [x] Build system for testing - @alastair
- [ ] Check differences between multi-runs on same machine (#179) - @dbogdanov 
- [ ] Compare output of same file on different architectures  (#179)
- [ ] Compare output of same file with different encodings (#179) [@alastair to get duplicates from abz server]
- [x] Merge OSX/Windows changes (#171, #178)
- [x] git tag 'final' release

**Comment by alastair** [comment]
We moved away from this a while ago, closing
